# Generated by Django 3.1.2 on 2020-11-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monyLifeApp', '0002_inversionpregunta_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='inversionpregunta',
            name='Descripcion',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
