# Generated by Django 3.1.2 on 2020-11-14 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monyLifeApp', '0003_inversionpregunta_descripcion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='preguntas_requisitos',
            unique_together=set(),
        ),
    ]
