# Generated by Django 3.1.2 on 2020-11-14 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monyLifeApp', '0005_auto_20201114_0202'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='preguntas_afecta',
            unique_together=set(),
        ),
    ]
