# Generated by Django 3.1.2 on 2020-11-14 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monyLifeApp', '0006_auto_20201114_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnos',
            name='Sueldo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
